<?php

return [
    'setting_types' => [
        'text' => 'متن ها',
        'input_file' => 'فایل ها',
        'array' => 'متن های چندتایی',
        'array_files' => 'فایل های چندتایی',
        'textarea' => 'توضیحات',
        'menu' => 'منو',
        'footer' => 'فوتر',
        'work_hours' => 'ساعات کاری',
        'ckeditor' => 'متن های ادیتور',
        'select' => 'سلکت باکس'
    ],
    'setting_partials' => [
        [
            "name" => "تنظیمات کلی",
            "theme_type" => ['theme1', 'theme2'],
            "partials" => [],
            "fields" => [
                [
                    "key" => "theme",
                    "value" => "theme1",
                    "p_name" => "انتخاب تم سایت",
                    "type" => "select_box",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "siteName_fa",
                    "value" => "نام سایت",
                    "p_name" => "عنوان فارسی سایت",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "siteName_en",
                    "value" => "lorem ipsum",
                    "p_name" => "عنوان انگلیسی سایت",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "first_page_shop_title",
                    "value" => "فروشگاه",
                    "p_name" => "عنوان فروشگاه در صفحه اول",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "logo",
                    "value" => null,
                    "p_name" => "لوگو",
                    "type" => "input_file",
                    "theme_type" => null,
                    "options" => [
                        "width" => 150,
                        "height" => 85,
                        "image" => "logo.jpg",
                    ],
                ],
                [
                    "key" => "favicon",
                    "value" => null,
                    "p_name" => "فوآیکون",
                    "type" => "input_file",
                    "theme_type" => null,
                    "options" => [
                        "width" => 64,
                        "height" => 64,
                        "image" => "favicon.jpg",
                    ],
                ],
                [
                    "key" => "desktop_header_banner",
                    "value" => null,
                    "p_name" => "بنر بالای صفحه در دسکتاپ",
                    "type" => "input_file",
                    "theme_type" => 'theme2',
                    "options" => [
                        "width" => 1900,
                        "height" => 75,
                    ],
                ],
                [
                    "key" => "desktop_header_banner_link",
                    "value" => null,
                    "p_name" => "لینک بنر بالای صفحه در دسکتاپ",
                    "type" => "text",
                    "theme_type" => 'theme2',
                    "options" => [],
                ],
                [
                    "key" => "mobile_header_banner",
                    "value" => null,
                    "p_name" => "بنر بالای صفحه در موبایل",
                    "type" => "input_file",
                    "theme_type" => 'theme2',
                    "options" => [
                        "width" => 1000,
                        "height" => 100,
                    ],
                ],
                [
                    "key" => "mobile_header_banner_link",
                    "value" => null,
                    "p_name" => "لینک بنر بالای صفحه در موبایل",
                    "type" => "text",
                    "theme_type" => 'theme2',
                    "options" => [],
                ],
                [
                    "key" => "location_header_title",
                    "value" => "عنوان مسیریابی هدر سایت",
                    "p_name" => "عنوان مسیریابی هدر سایت",
                    "type" => "text",
                    "theme_type" => 'theme1',
                    "options" => null,
                ],
                [
                    "key" => "site_header_title",
                    "value" => "عنوان تماس در هدر سایت",
                    "p_name" => "عنوان تماس در هدر سایت",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "tax",
                    "value" => "0",
                    "p_name" => "مالیات بر ارزش افزوده",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "basket_description",
                    "value" => null,
                    "p_name" => "متن صفحه ثبت سفارش",
                    "type" => "textarea",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "cart_payment_notice",
                    "value" => "قبل از پرداخت از خاموش بودن فیلترشکن(vpn) خود اطمینان حاصل کنید",
                    "p_name" => "متن هشدار مرحله پرداخت سبد خرید",
                    "type" => "textarea",
                    "theme_type" => null,
                    "options" => [
                        "alert" => "در صورت خالی بودن این فیلد، هشدار در صفحه «تایید و پرداخت» نمایش داده نمی‌شود.",
                        "alert_type" => "info",
                    ],
                ],
                [
                    "key" => "head_codes",
                    "value" => null,
                    "p_name" => "تگ های سئو در head",
                    "type" => "textarea",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "body_codes",
                    "value" => null,
                    "p_name" => "تگ های سئو در body",
                    "type" => "textarea",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "ecommerce_tracking_enabled",
                    "value" => 0,
                    "p_name" => "فعال‌سازی Ecommerce Tracking (GA4/GTM)",
                    "type" => "checkbox",
                    "theme_type" => null,
                    "options" => [
                        "alert" => "پس از فعال‌سازی، اسنیپت کامل Google Tag Manager باید در فیلدهای head و body بالا قرار گیرد.",
                        "alert_type" => "info",
                    ],
                ],
                [
                    "key" => "products_alert",
                    "value" => "",
                    "p_name" => "متن هشدار محصولات",
                    "type" => "textarea",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "disable_shop",
                    "value" => 0,
                    "p_name" => "غیرفعال کردن فروشگاهی",
                    "type" => "checkbox",
                    "theme_type" => 'theme1',
                    "options" => null,
                ],
                [
                    "key" => "require_postal_code",
                    "value" => 1,
                    "p_name" => "اجباری بودن کد پستی",
                    "type" => "checkbox",
                    "theme_type" => null,
                    "options" => null,
                ],
            ],
        ],
        [
            "name" => "تنظیمات منو",
            "theme_type" => ['theme1', 'theme2'],
            "partials" => [],
            "fields" => [
                [
                    "key" => "menu_links",
                    "value" => [
                        ["title" => "صفحه اصلی", "type" => "default", "url" => "/",],
                        ["title" => "خدمات", "type" => "service", "url" => "", "sidebyside" => "no"],
                        [
                            "title" => "نمونه کارها",
                            "type" => "default",
                            "url" => "portfolios",
                        ],
                        ["title" => "محصولات", "type" => "product", "url" => "", "sidebyside" => "no"],
                        [
                            "title" => "گالری",
                            "type" => "default",
                            "url" => "galleries",
                        ],
                    ],
                    "p_name" => "لینک های منو",
                    "type" => "menu",
                    "theme_type" => null,
                    "options" => null,
                ],
            ],
        ],
        [
            "name" => "تنظیمات صفحه اول",
            "theme_type" => ['theme1', 'theme2'],
            "partials" => [
                [
                    "name" => "اسلایدر",
                    "theme_type" => ['theme1'],
                    "fields" => [
                        [
                            "key" => "slider_h1_position",
                            "value" => "above",
                            "p_name" => "جایگاه تگ H1 صفحه اول",
                            "type" => "select",
                            "theme_type" => null,
                            "options" => [
                                'above' => 'بالای اسلایدر',
                                'below' => 'پایین اسلایدر',
                            ],
                        ],
                        [
                            "key" => "video_link",
                            "value" => null,
                            "p_name" => "لینک ویدیو صفحه اول",
                            "type" => "textarea",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "video_cover",
                            "value" => null,
                            "p_name" => "تصویر کاور ویدیو",
                            "type" => "input_file",
                            "theme_type" => 'theme1',
                            "options" => [
                                "width" => 510,
                                "height" => 300,
                                "image" => "cover-video.jpg",
                            ],
                        ],
                        [
                            "key" => "first_button",
                            "value" => "مشاهده خدمات",
                            "p_name" => "متن دکمه اول",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "first_link",
                            "value" => "/services",
                            "p_name" => "لینک دکمه اول",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "second_link",
                            "value" => "/portfolios",
                            "p_name" => "لینک دکمه دوم",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "second_button",
                            "value" => "نمونه کارها",
                            "p_name" => "متن دکمه دوم",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "slider_description",
                            "value" =>
                            "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد کتابهای زیادی در شصت و سه درصد گذشته حال و آینده ",
                            "p_name" => "توضیحات اسلایدر",
                            "type" => "textarea",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "slider_title",
                            "value" => "لورم ایپسوم متن ساختگی",
                            "p_name" => "متن روی اسلایدر",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                    ],
                ],
                [
                    "name" => "اسلایدر",
                    "theme_type" => ['theme2'],
                    "fields" => [
                        [
                            "key" => "slider_h1_position",
                            "value" => "above",
                            "p_name" => "جایگاه تگ H1 صفحه اول",
                            "type" => "select",
                            "theme_type" => null,
                            "options" => [
                                'above' => 'بالای اسلایدر',
                                'below' => 'پایین اسلایدر',
                            ],
                        ],
                    ],
                ],
                [
                    "name" => "خدمات",
                    "theme_type" => ['theme1'],
                    "fields" => [
                        [
                            "key" => "first_page_service_text",
                            "value" =>
                            "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد کتابهای زیادی در شصت و سه درصد گذشته حال و آینده ",
                            "p_name" => "متن قسمت خدمات صفحه اول",
                            "type" => "textarea",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "first_page_service_title",
                            "value" => "خدمات فروشگاه ما",
                            "p_name" => "عنوان قسمت خدمات صفحه اول",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                    ],
                ],
                [
                    "name" => "درباره ما",
                    "theme_type" => ['theme1', 'theme2'],
                    "fields" => [
                        [
                            "key" => "first_page_first_title",
                            "value" => "لورم ایپسوم متن ساختگی",
                            "p_name" => "عنوان اولین قسمت در صفحه اول",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "first_page_first_text",
                            "value" =>
                            "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد کتابهای زیادی در شصت و سه درصد گذشته حال و آینده ",
                            "p_name" => "متن اولین قسمت در صفحه اول",
                            "type" => "textarea",
                            "theme_type" => null,
                            "options" => null,
                        ],
                    ],
                ],
                [
                    "name" => "نمونه کار",
                    "theme_type" => ['theme1'],
                    "fields" => [

                        [
                            "key" => "first_page_sample_title",
                            "value" => "نمونه پروژه های فروشگاه",
                            "p_name" => "عنوان قسمت نمونه کار صفحه اول",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "sample_button",
                            "value" => "مشاهده تمام پروژه ها",
                            "p_name" => "دکمه مشاهده نمونه کار",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],

                    ],
                ],

                [
                    "name" => "گالری",
                    "theme_type" => ['theme1'],
                    "fields" => [
                        [
                            "key" => "first_page_gallery_title",
                            "value" => "گالری تصاویر و فیلم ها",
                            "p_name" => "عنوان گالری صفحه اول",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "first_page_gallery_text",
                            "value" => "پرسنل فروشگاه",
                            "p_name" => "متن گالری صفحه اول",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "gallery_button",
                            "value" => "مشاهده گالری فروشگاه ما ",
                            "p_name" => "دکمه گالری",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "first_page_gallery_animation",
                            "value" => "Lorem ipsum dolor sit amet, consectetur ",
                            "p_name" => "متن متحرک قسمت گالری در صفحه اول",
                            "type" => "textarea",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                    ],
                ],
                [
                    "name" => "متخصصان",
                    "theme_type" => ['theme1'],
                    "fields" => [
                        [
                            "key" => "first_page_team_title",
                            "value" => "متخصصان ما",
                            "p_name" => "عنوان قسمت متخصصان صفحه اول",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "first_page_team_text",
                            "value" => null,
                            "p_name" => "متن قسمت متخصصان صفحه اول",
                            "type" => "textarea",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                    ],
                ],
                [
                    "name" => "افتخارات",
                    "theme_type" => ['theme1'],
                    "fields" => [
                        [
                            "key" => "first_page_certificate_title",
                            "value" => "افتخارات و گواهینامه ها",
                            "p_name" => "عنوان قسمت گواهینامه صفحه اول",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "first_page_certificate_text",
                            "value" =>
                            "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است ",
                            "p_name" => "متن قسمت گواهینامه صفحه اول",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                    ],
                ],
                [
                    "name" => "پشتیبانی یا پکیج",
                    "theme_type" => ['theme1', 'theme2'],
                    "fields" => [
                        [
                            "key" => "first_page_package_title",
                            "value" => "پکیج های دکوراسیون",
                            "p_name" => "عنوان قسمت پکیج صفحه اول",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "first_page_package_text",
                            "value" => "تیم حرفه ای و متخصص فروشگاه",
                            "p_name" => "متن قسمت پکیج صفحه اول",
                            "type" => "textarea",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "online_support_link",
                            "value" => "https://t.me/(021) 88 23 56 22",
                            "p_name" => "لینک کامل برنامه پشتیبانی",
                            "type" => "textarea",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "support_call_text",
                            "value" => "تماس با پشتیبانی",
                            "p_name" => "متن قسمت پشتیبانی صفحه اول",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "support_call_hours",
                            "value" => "از ساعت ۱۰ صبح تا ۸ شب",
                            "p_name" => "ساعات پشتیبانی",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "online_support_text",
                            "value" => "ارتباط آنلاین با پشتیبانی",
                            "p_name" => "متن پشتیبانی آنلاین",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "online_support_hours",
                            "value" => "به صورت ۲۴ ساعته",
                            "p_name" => "ساعات پشتیبانی آنلاین پر صفحه اول",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "online_support_title",
                            "value" => "شماره تلگرام",
                            "p_name" => "عنوان پشتیبانی آنلاین",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "online_support_image",
                            "value" => null,
                            "p_name" => "تصویر پشتیبانی آنلاین در صفحه اول",
                            "type" => "input_file",
                            "theme_type" => null,
                            "options" => [
                                "width" => 132,
                                "height" => 130,
                                "image" => "support-img-bottom.jpg",
                            ],
                        ],
                    ],
                ],
                [
                    "name" => "محصول",
                    "theme_type" => ['theme1'],
                    "fields" => [
                        [
                            "key" => "timer_image",
                            "value" => null,
                            "p_name" => "تصویر بک گراند تایمر صفحه اول",
                            "type" => "input_file",
                            "theme_type" => 'theme1',
                            "options" => [
                                "width" => 1000,
                                "height" => 667,
                                "image" => "discounted-back.jpg",
                            ],
                        ],
                    ],
                ],
            ],
            "fields" => [],
        ],
        [
            "name" => "تنظیمات فوتر",
            "theme_type" => ['theme1', 'theme2'],
            "partials" => [
                [
                    "name" => "بخش های فوتر",
                    "theme_type" => ['theme1', 'theme2'],
                    "fields" => [
                        [
                            "key" => "enamad",
                            "value" => null,
                            "p_name" => "اینماد",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "footer_valids",
                            "value" => null,
                            "p_name" => "کدهای مربوط به اعتبار",
                            "type" => "array",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "footer_logo",
                            "value" => null,
                            "p_name" => "لوگو فوتر",
                            "type" => "input_file",
                            "theme_type" => 'theme1',
                            "options" => [
                                "width" => 150,
                                "height" => 85,
                                "image" => "logo-footer.jpg",
                            ],
                        ],
                        [
                            "key" => "footer_about_title",
                            "value" => "لورم ایپسوم",
                            "p_name" => "عنوان درباره ما فوتر",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "footer_about_text",
                            "value" =>
                            "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد کتابهای زیادی در شصت و سه درصد گذشته حال و آینده ",
                            "p_name" => "متن درباره ما فوتر",
                            "type" => "textarea",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "call_to_action_text",
                            "value" => "منتظر صدای گرم شما هستیم",
                            "p_name" => "متن تماس بگیرید در فوتر",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "phones_first_page_text",
                            "value" => "شماره های تماس",
                            "p_name" => "متن شماره های تماس در صفحه اول",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "service_in_footer",
                            "value" => 0,
                            "p_name" => " نمایش خدمات در فوتر ",
                            "type" => "checkbox",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "category_in_footer",
                            "value" => 1,
                            "p_name" => " نمایش دسته بندی در فوتر ",
                            "type" => "checkbox",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "service_title_footer",
                            "value" => " خدمات ما ",
                            "p_name" => "عنوان خدمات در فوتر",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "category_title_footer",
                            "value" => " دسته بندی ها ",
                            "p_name" => "عنوان دسته بندی ها در فوتر",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "gallery_title_footer",
                            "value" => " رویدادها ",
                            "p_name" => "عنوان گالری در منو و فوتر",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "sample_title_footer",
                            "value" => " نمونه کار ",
                            "p_name" => "عنوان نمونه کار در منو و فوتر",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "footer_links",
                            "value" => [
                                ["title" => "صفحه اصلی", "url" => "/"],
                                ["title" => "خدمات", "url" => "services"],
                                ["title" => "گالری", "url" => "galleries"],
                                ["title" => "اطلاعات تماس", "url" => "contact-us"],
                                ["title" => "درباره ما", "url" => "about-us"],

                            ],
                            "p_name" => "لینک های دسترسی سریع",
                            "type" => "footer",
                            "theme_type" => null,
                            "options" => null,
                        ],
                    ],
                ],
                [
                    "name" => "ساعت کاری",
                    "theme_type" => ['theme1', 'theme2'],
                    "fields" => [
                        [
                            "key" => "work_hours",
                            "value" => [
                                "شنبه" => ["from" => "10", "to" => "22"],
                                "یکشنبه" => ["from" => "10", "to" => "22"],
                                "دوشنبه" => ["from" => "10", "to" => "22"],
                                "سه شنبه" => ["from" => "10", "to" => "22"],
                                "چهارشنبه" => ["from" => "10", "to" => "22"],
                                "پنجشنبه" => ["from" => "10", "to" => "22"],
                                "جمعه" => ["from" => "10", "to" => "22"],
                            ],
                            "p_name" => "ساعت کاری",
                            "type" => "work_hours",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "work_hours_first_page",
                            "value" =>
                            "ما در ساعات کاری منعطف آماده ارائه خدمت به شما عزیزان هستیم.",
                            "p_name" => "توضیحات ساعات کاری صفحه اول",
                            "type" => "text",
                            "theme_type" => 'theme1',
                            "options" => null,
                        ],
                        [
                            "key" => "work_hours_first_page_title",
                            "value" => " ساعات کاری گالری ",
                            "p_name" => "عنوان قسمت ساعات کاری فوتر",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "work_hours_first_page_text",
                            "value" => "جهت رزرو می توانید با ما تماس بگیرید!",
                            "p_name" => "متن دکمه ساعات کاری فوتر",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                    ],
                ],
            ],
            "fields" => []
        ],
        [
            "name" => "تنظیمات ادز",
            "theme_type" => ['theme1', 'theme2'],
            "partials" => [],
            "fields" => [
                [
                    "key" => "ads_number",
                    "value" => null,
                    "p_name" => "شماره تلفن ادز",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "ads_text",
                    "value" => null,
                    "p_name" => "متن ادز",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "ads_show",
                    "value" => 0,
                    "p_name" => " نمایش ادز ",
                    "type" => "checkbox",
                    "theme_type" => null,
                    "options" => null,
                ],
            ],
        ],
        [
            "name" => "تنظیمات صفحات داخلی",
            "theme_type" => ['theme1', 'theme2'],
            "partials" => [
                [
                    "name" => "مشترک بین صفحات",
                    "theme_type" => ['theme1', 'theme2'],

                    "fields" => [
                        [
                            "key" => "image_header",
                            "value" => null,
                            "p_name" => "تصویر هدر صفحات داخلی",
                            "type" => "input_file",
                            "theme_type" => null,
                            "options" => [
                                "width" => 1920,
                                "height" => 350,
                                "image" => "service-header-detail.jpg",
                            ],
                        ],
                    ],
                ],
                [
                    "name" => "خدمات",
                    "theme_type" => ['theme1', 'theme2'],

                    "fields" => [
                        [
                            "key" => "service_description",
                            "value" =>
                            "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد کتابهای زیادی در شصت و سه درصد گذشته حال و آینده ",
                            "p_name" => "توضیحات لیست خدمات",
                            "type" => "ckeditor",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "service_header",
                            "value" => null,
                            "p_name" => "تصویر هدر صفحه جزییات خدمات",
                            "type" => "input_file",
                            "theme_type" => null,
                            "options" => [
                                "width" => 1920,
                                "height" => 350,
                                "image" => "service-header-detail.jpg",
                            ],
                        ],
                    ],
                ],
                [
                    "name" => "نمونه کار",
                    "theme_type" => ['theme1', 'theme2'],

                    "fields" => [
                        [
                            "key" => "portfolio_description",
                            "value" =>
                            "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد کتابهای زیادی در شصت و سه درصد گذشته حال و آینده ",
                            "p_name" => "توضیحات لیست نمونه کار",
                            "type" => "ckeditor",
                            "theme_type" => null,
                            "options" => null,
                        ],
                    ],
                ],
                [
                    "name" => "مطالب",
                    "theme_type" => ['theme1', 'theme2'],
                    "fields" => [
                        [
                            "key" => "blog_list_header",
                            "value" => null,
                            "p_name" => "تصویر هدر لیست مطالب",
                            "type" => "input_file",
                            "theme_type" => null,
                            "options" => [
                                "width" => 1920,
                                "height" => 350,
                                "image" => "blogs-header.jpg",
                            ],
                        ],
                    ],
                ],
                [
                    "name" => "همه محصولات",
                    "theme_type" => ['theme1', 'theme2'],

                    "fields" => [
                        [
                            "key" => "all_product_description",
                            "value" =>
                            "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد کتابهای زیادی در شصت و سه درصد گذشته حال و آینده ",
                            "p_name" => "توضیحات لیست همه محصولات",
                            "type" => "ckeditor",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "all_product_title",
                            "value" => "لیست همه محصولات",
                            "p_name" => "لیست همه محصولات",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                    ],
                ],
                [
                    "name" => "درباره ما",
                    "theme_type" => ['theme1', 'theme2'],

                    "fields" => [
                        [
                            "key" => "about_us",
                            "value" =>
                            "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد کتابهای زیادی در شصت و سه درصد گذشته حال و آینده ",
                            "p_name" => "صفحه درباره ما",
                            "type" => "ckeditor",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "about_us_page_title",
                            "value" => "درباره ما",
                            "p_name" => "عنوان صفحه ی درباره ما",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],

                    ],
                ],
                [
                    "name" => "قوانین و مقررات",
                    "theme_type" => ['theme1', 'theme2'],

                    "fields" => [
                        [
                            "key" => "terms_and_conditions",
                            "value" =>
                            "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. متن قوانین و مقررات فروشگاه خود را در این بخش وارد کنید.",
                            "p_name" => "صفحه قوانین و مقررات",
                            "type" => "ckeditor",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "terms_and_conditions_page_title",
                            "value" => "قوانین و مقررات",
                            "p_name" => "عنوان صفحه قوانین و مقررات",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "cart_terms_acceptance_enabled",
                            "value" => 0,
                            "p_name" => "فعال‌سازی تیک پذیرش قوانین در مرحله پرداخت",
                            "type" => "checkbox",
                            "theme_type" => null,
                            "options" => [
                                "alert" => "در صورت فعال بودن، مشتری قبل از ورود به درگاه باید قوانین را مطالعه کرده و تیک پذیرش را بزند.",
                                "alert_type" => "info",
                            ],
                        ],
                    ],
                ],
                [
                    "name" => "تماس با ما",
                    "theme_type" => ['theme1', 'theme2'],

                    "fields" => [
                        [
                            "key" => "contact_us_page_title",
                            "value" => "تماس با ما",
                            "p_name" => "عنوان صفحه ی تماس با ما",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],

                    ],
                ],
                [
                    "name" => "دسته بندی",
                    "theme_type" => ['theme1', 'theme2'],

                    "fields" => [
                        [
                            "key" => "category_description",
                            "value" =>
                            "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد کتابهای زیادی در شصت و سه درصد گذشته حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد ",
                            "p_name" => "توضیحات لیست دسته بندی",
                            "type" => "ckeditor",
                            "theme_type" => null,
                            "options" => null,
                        ],
                    ],
                ],
            ],
            "fields" => [],
        ],
        [
            "name" => "تنظیمات تماس",
            "theme_type" => ['theme1', 'theme2'],
            "partials" => [],
            "fields" => [
                [
                    "key" => "main_phone_number",
                    "value" => "02156378201",
                    "p_name" => "شماره تلفن اصلی",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "phone_numbers",
                    "value" => "02188602886",
                    "p_name" => "شماره ها",
                    "type" => "array",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "email",
                    "value" => "info@email.com",
                    "p_name" => "ایمیل",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "map",
                    "value" => "https://goo.gl/maps/8FoiwF8NSvFXZhgg9",
                    "p_name" => "نقشه",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "address",
                    "value" => "لورم ایپسوم",
                    "p_name" => "آدرس",
                    "type" => "textarea",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "phone_call",
                    "value" => "تماس فروشگاه ما",
                    "p_name" => "متن تماس",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],
            ],
        ],
        [
            "name" => "تنظیمات پرداخت بیعانه",
            "theme_type" => ['theme1', 'theme2'],
            "partials" => [],
            "fields" => [
                [
                    "key" => "cart_deposit",
                    "value" => 0,
                    "p_name" => "کف قیمت سبد برای فعال شدن بیعانه",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "deposit_price",
                    "value" => 0,
                    "p_name" => "مبلغ بیعانه",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "shaba_number",
                    "value" => null,
                    "p_name" => "شماره شبا",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],


            ],
        ],
        [
            "name" => "تنظیمات پیامک",
            "theme_type" => ['theme1', 'theme2'],
            "partials" => [
                [
                    "name" => "تنظیمات عمومی پیامک",
                    "theme_type" => ['theme1', 'theme2'],
                    "fields" => [
                        [
                            "key" => "kavenegar_key",
                            "value" => null,
                            "p_name" => "شناسه کاوه نگار",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => null,
                        ],
                        [
                            "key" => "admin_mobile",
                            "value" => null,
                            "p_name" => "تلفن ادمین برای ارسال پیامک",
                            "type" => "array",
                            "theme_type" => null,
                            "options" => null,
                        ],
                    ],
                ],
                [
                    "name" => "تنظیمات موجود/حراج شد خبرم کن",
                    "theme_type" => ['theme1', 'theme2'],
                    "fields" => [
                        [
                            "key" => "kavenegar_sender",
                            "value" => null,
                            "p_name" => "(شماره خط خدماتی(ارسال کننده کاوه نگار)",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => [
                                "alert" => "این امکان تنها برای خط های خدماتی و اختصاصی قابل استفاده است.",
                                "alert_type" => "warning"
                            ],
                        ],
                        [
                            "key" => "kavenegar_number_test",
                            "value" => null,
                            "p_name" => "شماره برای تست اطلاعات کاوه نگار",
                            "type" => "text",
                            "theme_type" => null,
                            "options" => [
                                "alert" => "یک شماره معتبر برای تست ارسال پیامک خط خدماتی وارد کنید.",
                                "alert_type" => "success"
                            ],
                        ],
                        [
                            "key" => "active_notifications",
                            "value" => 0,
                            "p_name" => "درخواست های موجود/حراج شد خبرم کن",
                            "type" => "checkbox",
                            "theme_type" => null,
                            "options" => null,
                        ],
                    ],
                ],
            ],
            "fields" => [],
        ],
        [
            "name" => "hidden",
            "theme_type" => ['theme1', 'theme2'],
            "partials" => [],
            "fields" => [
                [
                    "key" => "service_prefix",
                    "value" => "service",
                    "p_name" => "روت جزییات خدمات",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],

            ],
        ],
        [
            "name" => "تنظیمات اشتراک گذاری محصول",
            "theme_type" => ['theme1', 'theme2'],
            "partials" => [],
            "fields" => [
                [
                    "key" => "share_type",
                    "value" => "",
                    "p_name" => 'نوع پلتفرم اشتراک گذاری',
                    "type" => "select",
                    "theme_type" => null,
                    "options" => [
                        '' => '- پلتفرم را انتخاب کنید',
                        'aparat' => 'آپارات',
                        'bale' => 'بله',
                        'eitaa' => 'ایتا',
                        'facebook' => 'فیسبوک',
                        'instagram' => 'اینستاگرام',
                        'linkedin' => 'لینکداین',
                        'pinterest' => 'پینترست',
                        'Soroush' => 'سروش',
                        'telegram' => 'تلگرام',
                        'tiktok' => 'تیک تاک',
                        'whatsapp' => 'واتساپ',
                        'youtube' => 'یوتیوب',
                        'rubika' => 'روبیکا',
                        'castbox' => 'کست باکس'
                    ],
                ],

                [
                    "key" => "share_button_number",
                    "value" => "",
                    "p_name" => 'شماره یا آیدی(بدون پیش شماره و 0)',
                    "type" => "text",
                    "theme_type" => null,
                    "options" => "فقط اگر پلتفرم نیاز به شماره دارد (مثل واتساپ) وارد کنید. اگر آیدی وارد کردید، این فیلد را خالی بگذارید.",
                ],
                [
                    "key" => "share_button_link",
                    "value" => "",
                    "p_name" => 'لینک پلتفرم(غیر اجباری)',
                    "type" => "text",
                    "theme_type" => null,
                    "options" => "اگر این فیلد را پر کنید، لینک پیش‌فرض پلتفرم نادیده گرفته می‌شود و لینک شما مستقیماً استفاده می‌شود. می‌توانید آن را خالی بگذارید تا لینک پیش‌فرض بر اساس پلتفرم انتخابی ساخته شود.",
                ],
                [
                    "key" => "share_button_title",
                    "value" => "پیام",
                    "p_name" => "عنوان دکمه پیام",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "share_link_message",
                    "value" => "سلام، درباره این محصول میخواستم اطلاعات بگیرم",
                    "p_name" => "متن پیامی که   همراه لینک محصول به صورت پیش فرض ارسال می‌شود",
                    "type" => "text",
                    "theme_type" => null,
                    "options" => null,
                ],
                [
                    "key" => "share_button_display_type",
                    "value" => "normal",
                    "p_name" => "نوع نمایش دکمه اشتراک گذاری",
                    "type" => "select",
                    "theme_type" => null,
                    "options" => [
                        'normal' => 'نمایش ثابت',
                        'fixed' => 'نمایش شناور',
                    ],
                ],
                [
                    "key" => "show_share_button",
                    "value" => 0,
                    "p_name" => " نمایش دکمه مشاوره در جزئیات محصول",
                    "type" => "checkbox",
                    "theme_type" => null,
                    "options" => null,
                ],

            ],
        ],
    ]
];
